-- Remove grafana user
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT ON TABLES FROM grafana;
REVOKE SELECT ON ALL TABLES IN SCHEMA public FROM grafana;
REVOKE USAGE ON SCHEMA public FROM grafana;

DROP USER IF EXISTS grafana;

-- Set grafana user
CREATE USER grafana WITH ENCRYPTED PASSWORD 'grafana';

GRANT USAGE ON SCHEMA public TO grafana;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grafana;