[package]
name = "supbase_client"
version = "0.1.0"
edition = "2021"
#version.workspace = true
#edition.workspace = true

[dependencies]
hyper = { version = "0.14.27", features = ["client", "http1", "http2", "runtime"] }
tokio = { version = "1.29.1" }
