[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "hub",
    "core/*",
]

exclude = [
    "tests",
    "core/supbase_client"
]

[workspace.dependencies]
tokio = "1.29.1"
serde = "1.0"
serde_json = "1.0"