[package]
name = "config"
version.workspace = true
edition.workspace = true

[dependencies]
dotenvy = "0.15.7"
eyre = { workspace = true }

# Communication
url = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }

[features]
default = []
local_supabase = []